In [1]:
import numpy as np
data = np.array([1.5,-0.1,3],[0,-3,6.5]])
data

SyntaxError: closing parenthesis ']' does not match opening parenthesis '(' (3419794357.py, line 2)

In [2]:
import numpy as np
data = np.array([[1.5,-0.1,3],[0,-3,6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [4]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [5]:
data + data


array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [7]:
data.shape


(2, 3)

In [8]:
data.shape


(2, 3)

In [9]:
data.dtype

dtype('float64')

#4.1.1 创建ndarray

In [1]:
data1 = [[1,2,3,4],[5,6,7,8]]
arr1 = np.array(data2)

NameError: name 'np' is not defined

In [2]:
import numpy as np
data1 = [[1,2,3,4],[5,6,7,8]]
arr1 = np.array(data1)

NameError: name 'data2' is not defined

In [3]:
import numpy as np
data1 = [[1,2,3,4],[5,6,7,8]]
arr1 = np.array(data1)

In [4]:
arr1


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
data2 = [[1,2,3,4],[5,6,7,8]]

In [6]:
arr2 = np.array(data2)

In [7]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [9]:
arr2.ndim

2

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
np.empty((2,3,0))

array([], shape=(2, 3, 0), dtype=float64)

In [13]:
np.arrange(15)


AttributeError: module 'numpy' has no attribute 'arrange'

In [14]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#4.1.2 ndarray 的数据类型


In [15]:
arr1 = np.array([1,2,3],dtype = np.float64)

In [16]:
arr2 = np.array([1,2,3],dtype=nnp.in32)

NameError: name 'nnp' is not defined

In [17]:
arr2 = np.array([1,2,3],dtype=np.in32)

AttributeError: module 'numpy' has no attribute 'in32'

In [18]:
arr2 = np.array([1,2,3],dtype=np.int32)


In [19]:
arr1

array([1., 2., 3.])

In [20]:
arr2

array([1, 2, 3])

In [1]:
import numpy as np      

In [2]:
arr = np.array([3.7,-1.2,-2.6,0.5,12.9,10.1])

In [3]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [4]:
arr.astype(int32)

NameError: name 'int32' is not defined

In [6]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [7]:
int_array = np.arange(10)

In [8]:
calibers = np.array([.22,.270,.37,.380,.44,.50],dtype=np.float64)

In [9]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [10]:
arr = np.arange(10)

In [11]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr[5]

5

In [13]:
arr[5:8] = 12

In [14]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [15]:
arrwd = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [16]:
arrwd[2]

array([7, 8, 9])

In [17]:
arrwd[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
arrwd[2:]


array([[7, 8, 9]])

In [19]:
arrwd[2:]

array([[7, 8, 9]])

In [21]:
arrwd[1,:2]

array([4, 5])

In [23]:
arrwd[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [25]:
arrwd[:2,:2)

SyntaxError: closing parenthesis ')' does not match opening parenthesis '[' (3276592904.py, line 1)

In [26]:
arrwd[:2,:2]

array([[1, 2],
       [4, 5]])

In [27]:
names = np.array(["Bob",'Joe','Will','Bob','Will','Joe','Joe'],dtype='<U4')


In [28]:
data

NameError: name 'data' is not defined

In [29]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [30]:
data = np.array([4,7],[0,2],[-5,6],[0,0].[1,2],[-12,-4],[3,4]])

SyntaxError: closing parenthesis ']' does not match opening parenthesis '(' (860038855.py, line 1)

In [31]:
data = np.array([[4,7],[0,2],[-5,6],[0,0],[1,2],[-12,-4],[3,4]])

In [32]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [33]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [34]:
data[names == 'Bob']

array([[4, 7],
       [0, 0]])

#4.1.6 花式索引

In [35]:
arr = np.zeros((8,4))

In [36]:
for i in range(8):
    arr[i] = i

In [37]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [38]:
arr[[4,3,2,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [2., 2., 2., 2.],
       [6., 6., 6., 6.]])

In [39]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [40]:
arr = np.arange(32).reshape((8,4))

In [41]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [42]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [43]:
arr[[1,5,7,2],[:,[0,3,1,2]]

SyntaxError: invalid syntax (469438893.py, line 1)

In [44]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

#4.1.7 数组转置和轴对称

In [45]:
arr = np.arange(15).reshape(3,5)

In [46]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [47]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [48]:
arr = np.array([[0,1,0],[1,2,-2],[6,3,2],[-1,0,-1],[1,0,1]])

In [49]:
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [50]:
np.dot(arr.T,arr)

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [51]:
arr.T @ arr

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [53]:
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [54]:
arr.swapaxes(0,1)

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])

In [55]:
arr.swapaxes(1,2)

AxisError: axis2: axis 2 is out of bounds for array of dimension 2

In [56]:
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [57]:
arr.swapaxes(0,2)

AxisError: axis2: axis 2 is out of bounds for array of dimension 2

In [58]:
arr.swapaxes(1,0)

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])