In [1]:
import numpy as np
xarr = np.array([1.1,1.2,1.3,1.4,1.5])
yarr = np.array([2.1,2.2,2.3,2.4,2.5])


In [2]:
cond = np.array([True,False,True,True,False])

In [3]:
result = [(x if c else y) for x,y,c in zip(xarr,yarr,cond)]

In [4]:
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [5]:
result = np.where(cond,xarr,yarr)

In [6]:
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [7]:
rng = np.random.default_rng(seed = 12345)

In [8]:
arr = rng.standard_normal((4,4))

In [9]:
arr

array([[-1.42382504,  1.26372846, -0.87066174, -0.25917323],
       [-0.07534331, -0.74088465, -1.3677927 ,  0.6488928 ],
       [ 0.36105811, -1.95286306,  2.34740965,  0.96849691],
       [-0.75938718,  0.90219827, -0.46695317, -0.06068952]])

In [10]:
arr>0

array([[False,  True, False, False],
       [False, False, False,  True],
       [ True, False,  True,  True],
       [False,  True, False, False]])

In [11]:
np.where(arr>0,2,-2)

array([[-2,  2, -2, -2],
       [-2, -2, -2,  2],
       [ 2, -2,  2,  2],
       [-2,  2, -2, -2]])

In [12]:
np.where(arr>0,2,arr)

array([[-1.42382504,  2.        , -0.87066174, -0.25917323],
       [-0.07534331, -0.74088465, -1.3677927 ,  2.        ],
       [ 2.        , -1.95286306,  2.        ,  2.        ],
       [-0.75938718,  2.        , -0.46695317, -0.06068952]])

In [13]:
arr = rng.standard_normal((5,4))

In [14]:
arr

array([[ 0.78884434, -1.25666813,  0.57585751,  1.39897899],
       [ 1.32229806, -0.29969852,  0.90291934, -1.62158273],
       [-0.15818926,  0.44948393, -1.34360107, -0.08168759],
       [ 1.72473993,  2.61815943,  0.77736134,  0.8286332 ],
       [-0.95898831, -1.20938829, -1.41229201,  0.54154683]])

In [16]:
arr.mean()

0.17933634979615845

In [17]:
np.mean(arr)

0.17933634979615845

In [18]:
arr.sum()

3.586726995923169

In [19]:
arr.sum(0)

array([ 2.71870476,  0.30188842, -0.49975489,  1.0658887 ])

In [20]:
arr.mean(1)

array([ 0.37675318,  0.07598404, -0.2834985 ,  1.48722347, -0.75978045])

In [21]:
arr = np.array([0,1,2,3,4,5,6,7])

In [22]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28])

In [23]:
arr2 = arr.cumsum()

In [24]:
arr2

array([ 0,  1,  3,  6, 10, 15, 21, 28])

In [25]:
arr =np.array([[0,1,2],[3,4,5],[6,7,8]])

In [26]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
arr.cumsum(0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [28]:
arr[1]

array([3, 4, 5])

In [29]:
arr.cumsum(1)

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]])

In [30]:
%timeit arr.cumsum(1)

889 ns ± 34.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [31]:
%timeit for i in range(9)

SyntaxError: expected ':' (<unknown>, line 1)

In [32]:
%timeit for i in range(9):

SyntaxError: incomplete input (<unknown>, line 1)

In [33]:
%timeit for i in range(9): x+i

NameError: name 'x' is not defined

In [34]:
x = 0

In [35]:
%timeit for i in range(9): x+i

270 ns ± 3.11 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [36]:
%timeit for i in arr:
    x=0
    for j in i:
        x+=j

IndentationError: unexpected indent (1756081980.py, line 2)

In [37]:
%timeit for i in arr:
    for j in i:
        x+=j

IndentationError: unexpected indent (510851005.py, line 2)

In [38]:
%timeit for i in arr:for j in i: x+=j
       

SyntaxError: invalid syntax (<unknown>, line 1)

In [39]:
%timeit for i in arr:
            for j in i:
                x+=j

IndentationError: unexpected indent (40399353.py, line 2)

In [40]:
arr = rng.standard_normal(100)

In [41]:
arr

array([ 7.51939396e-01, -6.58760320e-01, -1.22867499e+00,  2.57557768e-01,
        3.12902918e-01, -1.30811690e-01,  1.26998312e+00, -9.29624577e-02,
       -6.61508890e-02, -1.10821447e+00,  1.35956851e-01,  1.34707776e+00,
        6.11440210e-02,  7.09146003e-02,  4.33654537e-01,  2.77483660e-01,
        5.30252387e-01,  5.36720969e-01,  6.18350015e-01, -7.95017456e-01,
        3.00030946e-01, -1.60270159e+00,  2.66798830e-01, -1.26162378e+00,
       -7.12708062e-02,  4.74049730e-01, -4.14853761e-01,  9.77165000e-02,
       -1.64041784e+00, -8.57258824e-01,  6.88281788e-01, -1.15452958e+00,
        6.50452389e-01, -1.38835995e+00, -9.07382457e-01, -1.09542531e+00,
        7.14569494e-03,  5.34359903e-01, -1.06580785e+00, -1.81472740e-01,
        1.62195180e+00, -3.17391946e-01, -8.15814967e-01,  3.86579017e-01,
       -2.23638926e-01, -7.01690809e-01, -1.79571318e+00,  8.18325622e-01,
       -5.71032902e-01,  7.85525063e-04, -1.06364272e+00,  1.30171450e+00,
        7.47872942e-01,  

In [42]:
(arr>0).sum()

51

In [43]:
(arr<0).sum()

49

In [44]:
bools = np.array([False,False,True,False])

In [45]:
bools.any()

True

In [46]:
bools.all()

False

In [47]:
arr  = rng.stamdard_normal(6)

AttributeError: 'numpy.random._generator.Generator' object has no attribute 'stamdard_normal'

In [48]:
arr  = rng.standard_normal(6)

In [49]:
arr

array([ 0.28208603, -0.62361213,  1.12182226,  0.84122103, -0.7758961 ,
        0.41071644])

In [50]:
arr.sort()

In [51]:
arr

array([-0.7758961 , -0.62361213,  0.28208603,  0.41071644,  0.84122103,
        1.12182226])

In [52]:
arr.sort(0)

In [53]:
arr

array([-0.7758961 , -0.62361213,  0.28208603,  0.41071644,  0.84122103,
        1.12182226])

In [54]:
arr.sort(1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [55]:
arr.sort(reverse = False)

TypeError: sort() got an unexpected keyword argument 'reverse'

In [56]:
arr2 = np.array([5,-10,7,1,0,-3])

In [57]:
sorted_arr2 = np.sort(arr2)

In [58]:
sorted_arr2

array([-10,  -3,   0,   1,   5,   7])

In [59]:
arr2

array([  5, -10,   7,   1,   0,  -3])

In [60]:
names = np.array(["Bob","Will","Joe","Bob","Will","Joe","Joe"])

In [61]:
np.unique()

TypeError: unique() missing 1 required positional argument: 'ar'

In [62]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [63]:
sorted(set(names))

['Bob', 'Joe', 'Will']

In [64]:
set(names)

{'Bob', 'Joe', 'Will'}

In [65]:
values = np.arrat([6,0,0,3,2,5,6])

AttributeError: module 'numpy' has no attribute 'arrat'

In [66]:
values = np.array([6,0,0,3,2,5,6])

In [67]:
np.inld(valuesm[2,3,6])

AttributeError: module 'numpy' has no attribute 'inld'

In [68]:
np.inld(values,[2,3,6])

AttributeError: module 'numpy' has no attribute 'inld'

In [69]:
np.in1d(values,[2,3,6])

array([ True, False, False,  True,  True, False,  True])