In [1]:
import pandas as pd
import numpy as np

In [2]:
obj = pd.Series([4.5,7.2,-5.3,3.6],index=["d","b","a","c"])

In [3]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [4]:
obj.T

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [5]:
obj2 = obj.reindex(["a","b","c","d","e"])

In [6]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [7]:
obj3 = pd.Series(["blue","purple","yellow"],index =[0,2,4])

In [8]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [9]:
obj3.reindex(np.arange(6),method="ffill")

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [10]:
frame = pd.DataFrame(np.arange(9),reshape(3,3),index = ["a","b","d",columns = ["Ohio","Texas","California"]

SyntaxError: '[' was never closed (2220161627.py, line 1)

In [11]:
frame = pd.DataFrame(np.arange(9),reshape(3,3),index = ["a","b","d"],columns = ["Ohio","Texas","California"])

NameError: name 'reshape' is not defined

In [12]:
frame = pd.DataFrame(np.arange(9),reshape((3,3)),index = ["a","b","d"],columns = ["Ohio","Texas","California"])

NameError: name 'reshape' is not defined

In [13]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),index = ["a","b","d"],columns = ["Ohio","Texas","California"])

In [14]:
frame = pd.DataFrame(np.arange(9).reshape(3,3),index = ["a","b","d"],columns = ["Ohio","Texas","California"])

In [15]:
frame

Ohio  Texas  California
a     0      1           2
b     3      4           5
d     6      7           8

In [16]:
frame2 = frame.reindex(index=["a","b","c","d"])

In [17]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   3.0    4.0         5.0
c   NaN    NaN         NaN
d   6.0    7.0         8.0

In [18]:
states = ["Texas","Utah","California"]

In [19]:
frame.reindex(columns = states)

Texas  Utah  California
a      1   NaN           2
b      4   NaN           5
d      7   NaN           8

In [20]:
frame.reindex(states,axis="columns")

Texas  Utah  California
a      1   NaN           2
b      4   NaN           5
d      7   NaN           8

In [21]:
frame.reindex(["a","c","d",rows)

SyntaxError: closing parenthesis ')' does not match opening parenthesis '[' (2788932504.py, line 1)

In [22]:
frame.reindex(["a","c","d","rows")

SyntaxError: closing parenthesis ')' does not match opening parenthesis '[' (235995234.py, line 1)

In [23]:
frame.reindex(["a","c","d"],rows)

NameError: name 'rows' is not defined

In [24]:
frame.reindex(["a","c","d"],"rows")

TypeError: DataFrame.reindex() takes from 1 to 2 positional arguments but 3 were given

In [25]:
frame.reindex(["a","c","d"],axis="rows")

Ohio  Texas  California
a   0.0    1.0         2.0
c   NaN    NaN         NaN
d   6.0    7.0         8.0

In [26]:
frame.loc[["a","d","c"],["California","Texas"]]

KeyError: "['c'] not in index"

In [27]:
frame.loc[["a","b","d"],["California","Texas"]]

California  Texas
a           2      1
b           5      4
d           8      7

In [28]:
obj = pd.Series(np.arange(5.),index=["a","b","c","d","e"]

SyntaxError: incomplete input (808586647.py, line 1)

In [29]:
obj = pd.Series(np.arange(5.),index=["a","b","c","d","e"])

In [30]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [31]:
new_obj=obj.drop("c")

In [32]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [33]:
obj.drop(["d","c"])

a    0.0
b    1.0
e    4.0
dtype: float64

In [34]:
data = pd.DataFrame(np.arange(16).reshape(4,4),index = ["Ohio","Colorado","Utah","New York"],columns=["one","two","three","four"])

In [35]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [36]:
data.drop(index=["Colorado","Ohio"])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [37]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [38]:
data.drop(columns=["two"])

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [39]:
obj = pd.Series(np.arange(4.),index=["a","b","c","d"])

In [40]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [41]:
obj[1]

C:\Users\Eirudy\AppData\Local\Temp\ipykernel_29248\2469632899.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[1]


1.0

In [42]:
obj['b']

1.0

In [43]:
obj[1]

C:\Users\Eirudy\AppData\Local\Temp\ipykernel_29248\2469632899.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[1]


1.0

In [44]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [45]:
data = pd.DataFrame(np.arange(16).reshape(4,4),index=["Ohio","Colorado","Utah","New York"],columns=[1,2,3,4])

In [46]:
data

1   2   3   4
Ohio       0   1   2   3
Colorado   4   5   6   7
Utah       8   9  10  11
New York  12  13  14  15

In [47]:
data[2]da

Ohio         1
Colorado     5
Utah         9
New York    13
Name: 2, dtype: int32

In [48]:
data[[3,1]]

3   1
Ohio       2   0
Colorado   6   4
Utah      10   8
New York  14  12

In [49]:
data[:2]

1  2  3  4
Ohio      0  1  2  3
Colorado  4  5  6  7

In [50]:
data[:1]

1  2  3  4
Ohio  0  1  2  3

In [51]:
data[:-1]

1  2   3   4
Ohio      0  1   2   3
Colorado  4  5   6   7
Utah      8  9  10  11

In [52]:
data[0:2]

1  2  3  4
Ohio      0  1  2  3
Colorado  4  5  6  7

In [53]:
data<5

1      2      3      4
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [54]:
data[data<5] = 0

In [55]:
data

1   2   3   4
Ohio       0   0   0   0
Colorado   0   5   6   7
Utah       8   9  10  11
New York  12  13  14  15

In [56]:
data.loc["Colorado"]

1    0
2    5
3    6
4    7
Name: Colorado, dtype: int32

In [57]:
data.loc["Colorado",[2,3]]

2    5
3    6
Name: Colorado, dtype: int32

In [58]:
data.iloc[2]

1     8
2     9
3    10
4    11
Name: Utah, dtype: int32

In [59]:
data.iloc[[2,1]]

1  2   3   4
Utah      8  9  10  11
Colorado  0  5   6   7

In [60]:
data.iloc[2,[3,0,1]]

4    11
1     8
2     9
Name: Utah, dtype: int32

In [61]:
data.loc[data.3>=2]

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3354270362.py, line 1)

In [62]:
data.loc[data.three>=2]

AttributeError: 'DataFrame' object has no attribute 'three'

In [63]:
data.loc[data.'3'>=2]

SyntaxError: invalid syntax (3291559145.py, line 1)

In [1]:
import pandas as pd
import numpy as np

In [2]:
ser = pd.Series(np.arange(3.)

SyntaxError: incomplete input (941122630.py, line 1)

In [3]:
ser = pd.Series(np.arange(3.))

In [4]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [5]:
ser[-1]

KeyError: -1

In [6]:
ser2 = pd.Series(np.arange(3.),index=['a','b','c'])

In [7]:
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [8]:
ser2[-2]

C:\Users\Eirudy\AppData\Local\Temp\ipykernel_33916\3711684725.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ser2[-2]


1.0

In [9]:
s1 = pd.Series([7.3,-2.5,3.4,1.5],index=["a","c","d","e"])

In [10]:
s2 = pd.Series([-2.1,3.6,-1.5,4,3.1],index=["a","c","e","f","g"])

In [11]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [12]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [13]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [14]:
df1 = pd.DataFrame(np.arange(9.).reshape(3,1),columns=list("bcd"),index = ["Ohio","Texas","Colorado"])

ValueError: cannot reshape array of size 9 into shape (3,1)

In [15]:
df1 = pd.DataFrame(np.arange(9.).reshape(3,3),columns=list("bcd"),index = ["Ohio","Texas","Colorado"])

In [16]:
df2 = pd.DataFrame(np.arange(12.).reshape(4,3),columns=list("bde"),index = ["Utah","Ohio","Texas","Oregon"]

SyntaxError: incomplete input (2563517628.py, line 1)

In [17]:
df2 = pd.DataFrame(np.arange(12.).reshape(4,3),columns=list("bde"),index = ["Utah","Ohio","Texas","Oregon"])

In [18]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [19]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [20]:
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [21]:
df1 = pd.DataFrame({"A":[1,2]})
df2 = pd.DataFrame({"B":[3,4]})

In [22]:
df1

A
0  1
1  2

In [23]:
df2

B
0  3
1  4

In [24]:
df1+df2

A   B
0 NaN NaN
1 NaN NaN

In [25]:
df1 = pd.DataFrame({"A":[1,2]},columns=list("ab"))

In [26]:
df1

Empty DataFrame
Columns: [a, b]
Index: []

In [27]:
df1 = pd.DataFrame({"A":[1,2]},index=list("ab"))

In [28]:
df1

A
a  1
b  2

In [29]:
arr = np.arange(12.),reshape(3,4))

SyntaxError: unmatched ')' (1817288463.py, line 1)

In [30]:
arr = np.arange(12.).reshape(3,4)

In [31]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [32]:
arr[0]

array([0., 1., 2., 3.])

In [33]:
arr-arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [34]:
frame = pd.DataFrame(np.arange(12.).reshape(4,3),columns=list("bde"),index=["Utah","Ohio","Texas","Oregon"])

In [35]:
series = frame.iloc[0]

In [36]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [37]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [38]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [39]:
series2 = pd.Series(np.arange(3),index=["b","e","f"])

In [40]:
series2

b    0
e    1
f    2
dtype: int32

In [41]:
frame+series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [42]:
frame.add(series2,fill_value=0)

NotImplementedError: fill_value 0 not supported.

In [43]:
frame.add(series2,fill_value=0.)

NotImplementedError: fill_value 0.0 not supported.

In [44]:
frame.add(series2,fill_value=1)

NotImplementedError: fill_value 1 not supported.

In [45]:
frame+series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [46]:
frame.add(series2)

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [47]:
series1+series2

NameError: name 'series1' is not defined

In [48]:
series+series2

b    0.0
d    NaN
e    3.0
f    NaN
dtype: float64

In [49]:
series.add(series2)

b    0.0
d    NaN
e    3.0
f    NaN
dtype: float64

In [50]:
series.add(series2,fill_value = 0)

b    0.0
d    1.0
e    3.0
f    2.0
dtype: float64

In [51]:
frame = pd.DataFrame(np.random.standard_normal((4,3)),columns=list("bde"),index=["Utah","Ohio","Texas","Oregon"])

In [52]:
frame

b         d         e
Utah    0.696711  0.286622  1.702981
Ohio   -0.701477 -0.462545  0.107675
Texas   1.424355 -0.530214  0.786815
Oregon  0.711257  1.772027  0.359902

In [53]:
np.abs(frame)

b         d         e
Utah    0.696711  0.286622  1.702981
Ohio    0.701477  0.462545  0.107675
Texas   1.424355  0.530214  0.786815
Oregon  0.711257  1.772027  0.359902

In [54]:
def f1(x):
    return x.max()-x.min()

In [55]:
frame.apply(f1)

b    2.125833
d    2.302241
e    1.595306
dtype: float64

In [56]:
frame.apply(f1,axis="columns")

Utah      1.416358
Ohio      0.809152
Texas     1.954569
Oregon    1.412125
dtype: float64

In [57]:
def f2(x):

SyntaxError: incomplete input (1070589753.py, line 1)

In [58]:
def f2(x):
    return pd.Series([x.min(),x.max()],index=["min","max"])

In [59]:
frame.apply(f2)

b         d         e
min -0.701477 -0.530214  0.107675
max  1.424355  1.772027  1.702981

In [60]:
obj = pd.Series([7,-5,7,4,2,0,4])

In [61]:
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [62]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64